update config

diff --git a/rootfs/sbin/lfs-chroot b/rootfs/sbin/lfs-chroot
--- a/rootfs/sbin/lfs-chroot
+++ b/rootfs/sbin/lfs-chroot
@@ -1,57 +1,52 @@
-#!/bin/sh
-#
-# script to enter chroot
-#
+#!/bin/bash
 
 printhelp() {
 	cat << EOF
 
 Usage:
-  $(basename $0) [command]
+  $(basename $0) <newroot> <command>
   
-If 'command' is unspecified, ${0##*/} will launch /bin/sh.
+(omit command to chroot only)
   
 EOF
 }
 
 msgerr() {
-	echo "ERROR: $*"
-}
-
-unmount() {
-	while true; do
-		mountpoint -q $1 || break
-		umount $1 2>/dev/null
-	done
+	echo -e "ERROR: $@"
 }
 	
-[ "$(id -u)" = "0" ] || {
+if [ "$UID" != "0" ]; then
 	msgerr "$(basename $0) need root access!"
 	printhelp
 	exit 1
-}
-
-LFS="/mnt/lfs"
-
-if [ -f ./config ]; then
-	. ./config
 fi
 
-[ -d "$LFS" ] || {
-	msgerr "Directory '$LFS' not exist!"
+LFS=$1
+
+if [ -z $1 ]; then
+	msgerr "Please set directory for chroot!"
 	printhelp
 	exit 1
-}
+fi
 
-if [ ! "$1" ]; then
-	CMD="/bin/sh"
-else
-	CMD=$*
+if [ ! -d $LFS ]; then
+	msgerr "Directory '$LFS' not exist"
+	printhelp
+	exit 1
+fi
+
+shift
+
+CMD=$@
+if [ -z $2 ]; then
+	CMD="/bin/bash --login"
 fi
 
 if [ -e /sys/firmware/efi/systab ]; then
 	EFI_SYSTEM=1
 fi
+
+pushd $LFS &>/dev/null
 
 mount --bind /dev $LFS/dev
 mount -t devpts devpts $LFS/dev/pts -o gid=5,mode=620
@@ -66,11 +61,9 @@ if [ -h $LFS/dev/shm ]; then
   mkdir -p $LFS/$(readlink $LFS/dev/shm)
 fi
 
-[ -f $LFS/etc/resolv.conf ] && {
-	backupresolvconf=1
-	mv $LFS/etc/resolv.conf $LFS/etc/resolv.conf.tmp
-}
 cp -L /etc/resolv.conf $LFS/etc
+
+echo ":: entering chroot to $LFS."
 
 chroot "$LFS" /usr/bin/env -i \
 HOME=/root \
@@ -80,18 +73,17 @@ PATH=/bin:/usr/bin:/sbin:/usr/sbin $CMD
 
 retval=$?
 
-[ "$backupresolvconf" = 1 ] && {
-	mv $LFS/etc/resolv.conf.tmp $LFS/etc/resolv.conf
-}
+popd &>/dev/null
 
-unmount $LFS/dev/pts
-unmount $LFS/dev
-unmount $LFS/run
-unmount $LFS/proc
+umount $LFS/dev/pts
+umount $LFS/dev
+umount $LFS/run
+umount $LFS/proc
 if [ -n "$EFI_SYSTEM" ]; then
-	unmount $LFS/sys/firmware/efi/efivars
+	umount $LFS/sys/firmware/efi/efivars
 fi
-unmount $LFS/sys
+umount $LFS/sys
+
+echo ":: chroot exited."
 
 exit $retval
-
diff --git a/scripts/03-mkiso b/scripts/03-mkiso
--- a/scripts/03-mkiso
+++ b/scripts/03-mkiso
@@ -2,27 +2,27 @@
 
 chroot_run() {
 	mount_pseudofs
-	cp -L /etc/resolv.conf $KFS/etc/
-	chroot $KFS $@
+	cp -L /etc/resolv.conf $LFS/etc/
+	chroot $LFS $@
 	retval=$?
 	umount_pseudofs
 	return $retval
 }
 
 mount_pseudofs() {
-	mount --bind /dev $KFS/dev
-	mount -t devpts devpts $KFS/dev/pts -o gid=5,mode=620
-	mount -t proc proc $KFS/proc
-	mount -t sysfs sysfs $KFS/sys
-	mount -t tmpfs tmpfs $KFS/run
+	mount --bind /dev $LFS/dev
+	mount -t devpts devpts $LFS/dev/pts -o gid=5,mode=620
+	mount -t proc proc $LFS/proc
+	mount -t sysfs sysfs $LFS/sys
+	mount -t tmpfs tmpfs $LFS/run
 }
 
 umount_pseudofs() {
-	unmount $KFS/dev/pts
-	unmount $KFS/dev
-	unmount $KFS/run
-	unmount $KFS/proc
-	unmount $KFS/sys
+	unmount $LFS/dev/pts
+	unmount $LFS/dev
+	unmount $LFS/run
+	unmount $LFS/proc
+	unmount $LFS/sys
 }
 
 unmount() {
@@ -56,10 +56,10 @@ printerror() {
 }
 
 CWD=$PWD
-KFS="/mnt/kfs"
-WORKDIR="$KFS/tmp"
+LFS="/mnt/lfs"
+WORKDIR="$LFS/tmp"
 WDIR="$WORKDIR/iso"
-LABEL="KFSLIVECD"
+LABEL="LFSLIVECD"
 OUTPUT="kfs-livecd-$(date +"%Y%m%d").iso"
 FILEDIR="$CWD/files"
 
@@ -71,46 +71,46 @@ rm -fr $WDIR
 mkdir -p $WDIR
 
 printstep "Preparing isolinux files..."
-mkdir -p $WDIR/{kfs,isolinux,boot}
+mkdir -p $WDIR/{lfs,isolinux,boot}
 for file in $isolinux_files; do
-	cp $KFS/usr/share/syslinux/$file $WDIR/isolinux || die "failed copying '$file'"
+	cp $LFS/usr/share/syslinux/$file $WDIR/isolinux || die "failed copying '$file'"
 done
 #cp isolinux/splash.png $WDIR/isolinux
 cp $FILEDIR/isolinux.cfg $WDIR/isolinux
 [ -d rootfs ] && cp -Ra rootfs $WDIR
 
 printstep "Make squash filesystem..."
-mksquashfs $KFS $WDIR/kfs/root.sfs \
+mksquashfs $LFS $WDIR/lfs/root.sfs \
 		-b 1048576 -comp xz -Xdict-size 100% \
-		-e $KFS/var/lib/pkg/src/* \
-		-e $KFS/var/lib/pkg/pkg/* \
-		-e $KFS/var/lib/pkg/work/* \
-		-e $KFS/tools/ \
-		-e $KFS/tmp/* 2>/dev/null || die "failed create squashed filesystem"
+		-e $LFS/var/lib/pkg/src/* \
+		-e $LFS/var/lib/pkg/pkg/* \
+		-e $LFS/var/lib/pkg/work/* \
+		-e $LFS/tools/ \
+		-e $LFS/tmp/* 2>/dev/null || die "failed create squashed filesystem"
 
 printstep "Preparing kernel and initramfs..."
-cp $KFS/boot/vmlinuz-kfs $WDIR/boot/vmlinuz || die "failed copying kernel"
-cp files/livecd.hook $KFS/etc/mkinitramfs.d
-kernver=$(file $KFS/boot/vmlinuz-kfs | cut -d ' ' -f9)
+cp $LFS/boot/vmlinuz-lfs $WDIR/boot/vmlinuz || die "failed copying kernel"
+cp files/livecd.hook $LFS/etc/mkinitramfs.d
+kernver=$(file $LFS/boot/vmlinuz-lfs | cut -d ' ' -f9)
 chroot_run mkinitramfs -k $kernver -a livecd -o /boot/initrd-live.img || die "failed create initramfs"
-mv $KFS/boot/initrd-live.img $WDIR/boot/initrd || die "failed copying initrd"
+mv $LFS/boot/initrd-live.img $WDIR/boot/initrd || die "failed copying initrd"
 
 printstep "Setup UEFI mode..."
 mkdir -p $WDIR/boot/{grub/{fonts,x86_64-efi},EFI}
-if [ -f $KFS/usr/share/grub/unicode.pf2 ];then
-	cp $KFS/usr/share/grub/unicode.pf2 $WDIR/boot/grub/fonts
+if [ -f $LFS/usr/share/grub/unicode.pf2 ];then
+	cp $LFS/usr/share/grub/unicode.pf2 $WDIR/boot/grub/fonts
 fi
 if [ -f $WDIR/isolinux/splash.png ]; then
 	cp $WDIR/isolinux/splash.png $WDIR/boot/grub/
 fi
 echo "set prefix=/boot/grub" > $WDIR/boot/grub-early.cfg
-cp -a $KFS/usr/lib/grub/x86_64-efi/*.{mod,lst} $WDIR/boot/grub/x86_64-efi || die "Failed copying efi files"
+cp -a $LFS/usr/lib/grub/x86_64-efi/*.{mod,lst} $WDIR/boot/grub/x86_64-efi || die "Failed copying efi files"
 cp $FILEDIR/grub.cfg $WDIR/boot/grub/
 
 grub-mkimage -c $WDIR/boot/grub-early.cfg -o $WDIR/boot/EFI/bootx64.efi -O x86_64-efi -p "" iso9660 normal search search_fs_file
 modprobe loop
 dd if=/dev/zero of=$WDIR/boot/efiboot.img count=4096
-mkdosfs -n KFSLIVECD-UEFI $WDIR/boot/efiboot.img || die "Failed mkdosfs"
+mkdosfs -n LFSLIVECD-UEFI $WDIR/boot/efiboot.img || die "Failed mkdosfs"
 mkdir -p $WDIR/boot/efiboot
 mount -o loop $WDIR/boot/efiboot.img $WDIR/boot/efiboot || die "Failed mount efiboot.img"
 mkdir -p $WDIR/boot/efiboot/EFI/boot
@@ -121,7 +121,7 @@ rm -fr $WDIR/boot/efiboot
 printstep "Making the iso..."
 rm -f $OUTPUT
 xorriso -as mkisofs \
-    -isohybrid-mbr $KFS/usr/share/syslinux/isohdpfx.bin \
+    -isohybrid-mbr $LFS/usr/share/syslinux/isohdpfx.bin \
     -c isolinux/boot.cat \
     -b isolinux/isolinux.bin \
     -no-emul-boot \
